### ISSUE TITLE
sdist is unusable

### ISSUE THREAD

**Issue by mtelka** [saltstack/pytest-salt-factories#158]
The sdist package at PyPI is unusable because it basically contains almost no files.  The sdist contains several directories but all of them are empty:
```
$ wget https://files.pythonhosted.org/packages/67/98/87d7a4f2a14681ee10e7032c8be0871e966037d650a4c8dfd7b6b75a0d40/pytest-salt-factories-0.912.2.tar.gz
$ tar xf pytest-salt-factories-0.912.2.tar.gz
$ find pytest-salt-factories-0.912.2 -type d
pytest-salt-factories-0.912.2
pytest-salt-factories-0.912.2/requirements
pytest-salt-factories-0.912.2/docs
pytest-salt-factories-0.912.2/tests
pytest-salt-factories-0.912.2/examples
pytest-salt-factories-0.912.2/src
pytest-salt-factories-0.912.2/.github
pytest-salt-factories-0.912.2/changelog
$ find pytest-salt-factories-0.912.2 -type f
pytest-salt-factories-0.912.2/CHANGELOG.rst
pytest-salt-factories-0.912.2/LICENSE
pytest-salt-factories-0.912.2/MANIFEST.in
pytest-salt-factories-0.912.2/README.rst
pytest-salt-factories-0.912.2/setup.cfg
pytest-salt-factories-0.912.2/.readthedocs.yaml
pytest-salt-factories-0.912.2/pytest.ini
pytest-salt-factories-0.912.2/setup.py
pytest-salt-factories-0.912.2/PKG-INFO
pytest-salt-factories-0.912.2/pyproject.toml
pytest-salt-factories-0.912.2/.gitignore
$
```

**Comment by mtelka** [comment]
I tried github tarball and it does not work either:
```
$ /usr/bin/python3.9 -m build --wheel --no-isolation
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/vendor-packages/build/__main__.py", line 24, in <module>
    from build.env import IsolatedEnvBuilder
  File "/usr/lib/python3.9/vendor-packages/build/env.py", line 26, in <module>
    import virtualenv
  File "/usr/lib/python3.9/vendor-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/usr/lib/python3.9/vendor-packages/virtualenv/run/__init__.py", line 15, in <module>
    from .plugin.creators import CreatorSelector
  File "/usr/lib/python3.9/vendor-packages/virtualenv/run/plugin/creators.py", line 6, in <module>
    from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
  File "/usr/lib/python3.9/vendor-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 5, in <module>
    from virtualenv.create.creator import Creator
  File "/usr/lib/python3.9/vendor-packages/virtualenv/create/creator.py", line 13, in <module>
    from virtualenv.discovery.cached_py_info import LogCmd
  File "/usr/lib/python3.9/vendor-packages/virtualenv/discovery/cached_py_info.py", line 25, in <module>
    _CACHE[Path(sys.executable)] = PythonInfo()
  File "/usr/lib/python3.9/vendor-packages/virtualenv/discovery/py_info.py", line 100, in __init__
    self.distutils_install = self._distutils_install().copy()
  File "/usr/lib/python3.9/vendor-packages/virtualenv/discovery/py_info.py", line 183, in _distutils_install
    d = dist.Distribution({"script_args": "--no-user-cfg"})  # conf files not parsed so they do not hijack paths
  File "/usr/lib/python3.9/vendor-packages/setuptools/dist.py", line 486, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.9/vendor-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/usr/lib/python3.9/vendor-packages/setuptools/dist.py", line 925, in finalize_options
    ep(self)
  File "/usr/lib/python3.9/vendor-packages/setuptools_scm/integration.py", line 127, in infer_version
    _assign_version(dist, config)
  File "/usr/lib/python3.9/vendor-packages/setuptools_scm/integration.py", line 63, in _assign_version
    _version_missing(config)
  File "/usr/lib/python3.9/vendor-packages/setuptools_scm/__init__.py", line 108, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /tmp/pytest-salt-factories-0.912.2.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
$
```

**Comment by s0undt3ch** [comment]
I'd suggest trying the latest RC, that's what the salt test suite is using. It's not 1.0.0 yet but it's close.

**Comment by mtelka** [comment]
If the latest rc is both close to 1.0.0 and used by the salt test suite then what blocks the 1.0.0 release?  The development process is very slow.  Exactly as one would expect from a production release.  Thank you.

**Comment by s0undt3ch** [comment]
> If the latest rc is both close to 1.0.0 and used by the salt test suite then what blocks the 1.0.0 release? The development process is very slow. Exactly as one would expect from a production release. Thank you.

We need to expand docs and refine some usage regarding testing salt packages, then I think we'll make a 1.0.0
